### ISSUE TITLE
NPE thrown

### ISSUE THREAD

**Issue by longshorej** [landlord/landlord#38]
After running `landlord` in a loop, I can eventually get it to cause `landlordd` to throw an NPE, I think on a `Thread` instance. I assume it's a race condition and we need to check for null.

command: `while [ true ]; do { echo Testing... | landlord/target/release/landlord -cp landlordd/test/target/scala-2.12/classes "-Dgreeting=Welcome!" example.Hello ArgOne ArgTwo; }; done`

```
Slf4jLogger started
Ready.
An internal error has occurred within landlord given process 0. Stacktrace follows.
java.lang.NullPointerException
	at com.github.huntc.landlord.JvmExecutor$$anonfun$starting$1$$anon$1.waitForTermination$1(JvmExecutor.scala:269)
	at com.github.huntc.landlord.JvmExecutor$$anonfun$starting$1$$anon$1.$anonfun$uncaughtException$1(JvmExecutor.scala:278)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by longshorej** [comment]
Here's another one I found after fixing the above, hrm..

```
java.lang.NullPointerException: null
	at akka.stream.impl.io.OutputStreamSourceStage$OutputStreamSourceLogic$1.postStop(OutputStreamSourceStage.scala:140)
	at akka.stream.impl.fusijava.lang.NullPointerException: null
	at akka.stream.impl.io.OutputStreamSourceStage$OutputStreamSourceLogic$1.postStop(OutputStreamSourceStage.scala:140)
	at akka.stream.impl.fusing.GraphInterpreter.finalizeStage(GraphInterpreter.scala:571)
	at akka.stream.impl.fusing.GraphInterpreter.afterStageHasRun(GraphInterpreter.scala:552)
	at akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:467)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:468)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:745)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:760)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:670)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
ng.GraphInterpreter.finalizeStage(GraphInterpreter.scala:571)
	at akka.stream.impl.fusing.GraphInterpreter.afterStageHasRun(GraphInterpreter.scala:552)
	at akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:467)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:468)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:745)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:760)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:670)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by longshorej** [comment]
I think this is code in Akka is race prone: https://github.com/akka/akka/blob/v2.5.12/akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala#L113-L143

L126 can execute between L139 and L140, causing NPE. I'd think the best fix is to just catch an NPE there, WDYT @huntc?
