### ISSUE TITLE
Tests failing on Windows 10 x64

### ISSUE THREAD

**Issue by longshorej** [landlord/landlord#67]
I suspect this won't be too difficult to fix, and acknowledge it's low priority. That being said, I gave this a whirl on Windows 10 tonight.

Naturally, UNIX domain sockets will not work (though they may under WSL), but TCP should.

```sbt
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from C:\Users\longshorej\work\farmco\landlord\landlordd\project
[info] Loading settings from build.sbt ...
[info] Set current project to landlordd (in build file:/C:/Users/longshorej/work/farmco/landlord/landlordd/)
[info] sbt server started at local:sbt-server-3d5c7c6b5da8d001a17c
sbt:landlordd> daemon/test
[info] JavaArgsSpec:
[info] ThreadGroupMappingsSpec:
[info] parse
[info] A thread group mapping
[info] - should Accept just two regular classpath arg and the main class
[info] - should return the fallback when not inited
[info] - should Accept just a glob classpath arg and the main class
[info] - should return the inited value when inited
[info] - should return the fallback value when inited but then destroyed
[info] A thread group input stream
[info] - should read from the fallback in case of no others being declared
[info] - should read from the thread group stream given the init
[info] A thread group print stream
[info] - should Return just the main class when no args
[info] - should Return the main class and args
[info] - should write to the fallback in case of no others being declared when using the write byte method
[info] - should Parse properties
[info] - should write to the fallback in case of no others being declared when using the write array method
[info] - should write to the thread group stream given the init using the write array method
[info] - should Fail when given invalid flags
[info] A thread group's properties
[info] - should return the standard user.dir
[info] - should return an overridden user.dir when accessed via an inited thread
[info] A thread group's security manager
[info] - should permit exit
[info] - should not permit exit when accessed via an inited thread
Slf4jLogger started
SLF4J: A number (3) of logging calls during the initialization phase have been intercepted and are
SLF4J: now being replayed. These are subject to the filtering rules of the underlying logging system.
SLF4J: See also http://www.slf4j.org/codes.html#replay
Slf4jLogger started
Slf4jLogger started
Slf4jLogger started
[info] ProcessParameterParserSpec:
[info] TarStreamWriterSpec:
[info] The ProcessParameterParser
[info] The TarStreamWriter
[info] - should Write out a valid stream of Tar input
[info] - should produce a flow of ProcessInputParts in the required order given a valid input
[info] - should Reject an invalid stream of Tar input by failing the future
[info] JvmExecutorSpec:
[info] The classpath resolver
[info] - should resolve a non-glob
[info] - should resolve a glob *** FAILED ***
[info]   java.nio.file.InvalidPathException: Illegal char <*> at index 4: lib/*
[info]   at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
[info]   at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
[info]   at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
[info]   at sun.nio.fs.WindowsPath.parse(Unknown Source)
[info]   at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
[info] MainSpec:
[info]   at java.nio.file.Paths.get(Unknown Source)
[info] Main
[info]   at com.github.huntc.landlord.JvmExecutorSpec.$anonfun$new$3(JvmExecutorSpec.scala:40)
[info] - should process input for launching a process
[info]   at org.scalatest.AsyncWordSpecLike.transformToOutcomeParam$1(AsyncWordSpecLike.scala:136)
[info] - should receive a process id and signal when killing a process
[info]   at org.scalatest.AsyncWordSpecLike.$anonfun$registerTestToRun$2(AsyncWordSpecLike.scala:137)
[info] - should receive ??? with an unknown command
[info] JvmExecutorReaper
[info]   at org.scalatest.AsyncTestSuite.$anonfun$transformToOutcome$1(AsyncTestSuite.scala:240)
[info] - should register two actors and receive done with one having stopped and the other acting upon shutting down
[info]   ...
[info] - should don't register an actor but receive done upon shutting down
[info] The JVMExecutor
[info] - should start a process that then outputs stdin, ends and shuts everything down *** FAILED ***
[info]   123 equaled 123, but "...t #1: Hello World #1[
[info]   Argument #2: Hi #2
[info]   This is a test
[info]   Hello World
]info]   Good Bye!
[info]   " did not equal "...t #1: Hello World #1[
[info]   Argument #2: Hi #2
[info]   This is a test
[info]   Hello World
[info]   Good Bye!]
[info]   " (JvmExecutorSpec.scala:151)
[info] activeThreads
[info] - should work
[info] memberOfThreadGroup
[info] - should work
[info] removeShutdownHooks
[info] - should work
[info] Run completed in 5 seconds, 234 milliseconds.
[info] Total number of tests run: 32
[info] Suites: completed 6, aborted 0
[info] Tests: succeeded 30, failed 2, canceled 0, ignored 0, pending 0
[info] *** 2 TESTS FAILED ***
[error] Failed tests:
[error]         com.github.huntc.landlord.JvmExecutorSpec
[error] (daemon / Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 9 s, completed Jul 5, 2018 9:03:51 PM
```

Workaround to skip tests and stage anyways:

```powershell
 sbt compile "project daemon" "set Test / Keys.test := {}" stage
```

This at least results in `landlordd` starting, though I haven't tried further than that yet.

```
PS C:\Users\longshorej\work\farmco\landlord> landlordd/daemon/target/universal/stage/bin/landlordd -H tcp://127.0.0.1:12
34
Slf4jLogger started
TCP ready on 127.0.0.1:1234
```

**Comment by longshorej** [comment]
Client fails to build due to dependency on `chan-signal` which is used to handle POSIX signals. I suspect this wouldn't be too hard to exclude from Windows builds but don't know the mechanisms offhand.

```
   Compiling chan-signal v0.3.1
error[E0432]: unresolved import `libc::SIGHUP`
   --> C:\Users\longshorej\.cargo\registry\src\github.com-1ecc6299db9ec823\chan-signal-0.3.1\src\lib.rs:128:5
    |
128 |     SIGHUP, SIGINT, SIGQUIT, SIGILL, SIGABRT, SIGFPE, SIGKILL,
    |     ^^^^^^ no `SIGHUP` in the root

error[E0432]: unresolved import `libc::SIGINT`
   --> C:\Users\longshorej\.cargo\registry\src\github.com-1ecc6299db9ec823\chan-signal-0.3.1\src\lib.rs:128:13
    |
128 |     SIGHUP, SIGINT, SIGQUIT, SIGILL, SIGABRT, SIGFPE, SIGKILL,
    |             ^^^^^^ no `SIGINT` in the root

error[E0432]: unresolved import `libc::SIGQUIT`
   --> C:\Users\longshorej\.cargo\registry\src\github.com-1ecc6299db9ec823\chan-signal-0.3.1\src\lib.rs:128:21
    |
128 |     SIGHUP, SIGINT, SIGQUIT, SIGILL, SIGABRT, SIGFPE, SIGKILL,
    |                     ^^^^^^^ no `SIGQUIT` in the root

error[E0432]: unresolved import `libc::SIGILL`
   --> C:\Users\longshorej\.cargo\registry\src\github.com-1ecc6299db9ec823\chan-signal-0.3.1\src\lib.rs:128:30
    |
128 |     SIGHUP, SIGINT, SIGQUIT, SIGILL, SIGABRT, SIGFPE, SIGKILL,
    |                              ^^^^^^ no `SIGILL` in the root

error[E0432]: unresolved import `libc::SIGABRT`
   --> C:\Users\longshorej\.cargo\registry\src\github.com-1ecc6299db9ec823\chan-signal-0.3.1\src\lib.rs:128:38
    |
128 |     SIGHUP, SIGINT, SIGQUIT, SIGILL, SIGABRT, SIGFPE, SIGKILL,
    |                                      ^^^^^^^ no `SIGABRT` in the root

error[E0432]: unresolved import `libc::SIGFPE`
   --> C:\Users\longshorej\.cargo\registry\src\github.com-1ecc6299db9ec823\chan-signal-0.3.1\src\lib.rs:128:47
    |
128 |     SIGHUP, SIGINT, SIGQUIT, SIGILL, SIGABRT, SIGFPE, SIGKILL,
    |                                               ^^^^^^ no `SIGFPE` in the root

error[E0432]: unresolved import `libc::SIGKILL`
   --> C:\Users\longshorej\.cargo\registry\src\github.com-1ecc6299db9ec823\chan-signal-0.3.1\src\lib.rs:128:55
    |
128 |     SIGHUP, SIGINT, SIGQUIT, SIGILL, SIGABRT, SIGFPE, SIGKILL,
    |                                                       ^^^^^^^ no `SIGKILL` in the root

error[E0432]: unresolved import `libc::SIGSEGV`
   --> C:\Users\longshorej\.cargo\registry\src\github.com-1ecc6299db9ec823\chan-signal-0.3.1\src\lib.rs:129:5
    |
129 |     SIGSEGV, SIGPIPE, SIGALRM, SIGTERM, SIGUSR1, SIGUSR2,
    |     ^^^^^^^ no `SIGSEGV` in the root
```

**Comment by longshorej** [comment]
Also to note, Landlord via Docker on Windows works as it's using a Linux virtual machine.
